### PR TITLE
Text changes

### PR DESCRIPTION
**Pull request by awoflaherty**
Expanded ballot measure text.  
Changed ballot measure yes/no response option text to Yes/No.  
Capitalized Precinct in another area for consistency.

### CODE REVIEW

**Comment by awoflaherty** [comment]
@cwulfman 
I tried to consistently change in both xml and json files.  However, the ballot measure text appeared to be missing (?) from json file.  Below is the text I am trying to add including hard returns.  Please advise me on issues and next steps.  Thanks

Initiative Measure No 0101 concerns sales tax.

Shall Gadget County increase its sales tax from 1% to 1.1% for the purpose of raising additional revenue to fund expanded air traffic control operations?  Funding is to update its air traffic control system, make investments in safety and next-generation systems, and address the impact of aviation on climate change.

Should this measure be enacted into law?

**Comment by cwulfman** [comment]
Replace line 185 with the following:

```json
"@type": "ElectionResults.BallotMeasureContest",
"FullText": {
                        "@type": "ElectionResults.InternationalizedText",
                        "Text" : [
                            {
                                "@type": "ElectionResults.LanguageString",
                                "Content": "Initiative Measure No 0101 concerns sales tax.\nShall Gadget County increase its sales tax from 1% to 1.1% for the purpose of raising additional revenue to fund expanded air traffic control operations? Funding is to update its air traffic control system, make investments in safety and next-generation systems, and address the impact of aviation on climate change.\nShould this measure be enacted into law?"
                            }
                        ]
```

**Comment by awoflaherty** [comment]
Replaced this on line 285, not 185, lol.  Also, I had an extra 
],
on line 287, so I deleted it.  But it may mean there is a missing 
[
instead.

**Comment by cwulfman** [comment]
Accepting this PR now, so I can work on example 2, following conversation with EJS

**Pull request merged**
